---
- hosts: all
  become: true
  tasks:
    - name: Install packages haproxy
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
          - haproxy

      - name: Restart haproxy
      service:
        name: kubelet
        state: restarted